### Test file for Visual Studio Code REST client extension

GET https://localhost:7075/

###
POST https://localhost:7075/login
Content-Type: application/json

{
    "username": "eca",
    "password": "password"
}

###
GET https://localhost:7075/private
Authorization: Bearer <your token here>